### ISSUE TITLE
Support PHP 5.3 by changing array type

### ISSUE THREAD

**Issue by ReneBechKorsgaard** [QuickPay/quickpay-php-client#15]
Hello.

I am getting the following error, when trying to initialize a client using an api_key:
Parse error: syntax error, unexpected '[' in /home/sites/dev.123annonce.dk/web/QuickPay/API/Response.php on line 89

when I go to that place in the code my editor also reports the lines to contain syntax errors. The lines in question are in the end of the function as_raw:
return [$this->status_code,
			[	'sent' => $sent_headers,
				'received' => $this->received_headers,
			],
			$this->response_data,
		];

**Comment by HH101** [comment]
Hello. 

I'm not sure of the consequenses but if you change the code to:

`return $this->response_data;`

it seems to work.

**Comment by lsolesen** [comment]
You are probably on PHP 5.3. This way to use code has been introduced in PHP 5.4. However, it should be possible to change it to be compatible with PHP 5.3 by using regular arrays instead. But maybe it would be even better for you to upgrade your PHP version, as 5.3 is deprecated and newer versions are both faster and more secure.

**Comment by acidtv** [comment]
I'm also on PHP 5.3 and not (yet) in a position to upgrade. 

Would you accept a pull request to make this library PHP 5.3 compatible?

**Comment by lsolesen** [comment]
Yes. Remember to update composer php requirement and please make sure that
there is test coverage for the changes.
Den 23/03/2016 11.34 skrev "Alex" <notifications@github.com>:

**Comment by acidtv** [comment]
Ok, I've made the changes and it works. 

Though the problem is that phpunit's dependencies require libs that won't install on PHP 5.3. Funny thing is that if I install the dev libs on my host machine and run the tests in my container with PHP 5.3, the tests do pass :)

Because of that I don't think we can have Travis also run the tests on PHP 5.3 unless we use an older phpunit version.

I can still do a pull request if you're interested. This is my branch if you're interested: https://github.com/1200wd/quickpay-php-client/tree/patch-php53

Alex

**Comment by lsolesen** [comment]
As long as the tests pass on 5.5 on Travis, it is cool. Though make sure
that the changed parts is covered by the tests.
Den 23/03/2016 12.52 skrev "Alex" <notifications@github.com>:

**Comment by acidtv** [comment]
I've issued a pull request now :)

**Comment by lsolesen** [comment]
This has been fixed here: https://github.com/QuickPay/quickpay-php-client/commit/1632b845e22f780b99c97d4c6cf552e5a8572457
